package exceptions;

public class MainExceptions{

    public static void main(String[] args){
        /*String nombre = null;
        try{
            System.out.println("El largo del nombre es:"+ nombre.length());

        }catch (NullPointerException e){
            System.out.println("El valor del nombre es nulo.\nSofia");
        }*/

        /*
        String nombre = null;
        try{
            if(nombre == null){
                throw new Exception("El nombre es nulo");
                //System.out.println("El largo del nombre es:"+ nombre.length());
            }
        }catch(Exception e){
            System.err.println(e);

        }
        */

        /*
        String nombre = null;
        try{
            Manejo.manejarExcp();
            //System.out.println("El largo del nombre es:"+ nombre.length()) throw new NullPointerException("El nombre es nulo");
        }catch(NullPointerException e){
            //System.out.println(e);
            System.out.println(e);
            System.out.println("Sofia.");
        }*/


    }
}
